test44

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -89,11 +89,13 @@ jobs:
       # 6️⃣ Run Laravel tests
       # -------------------------
       - name: Run backend tests
+        id: backend_tests
         working-directory: Backend
-        run: php artisan test
+        run: php artisan test || echo "tests_failed=true" >> $GITHUB_OUTPUT
         env:
           DB_CONNECTION: sqlite
           DB_DATABASE: database/database.sqlite # This will use the file we touched in step 4
+
 
       # -------------------------
       # 7️⃣ Setup Node.js
