small changes : unit backend test  jobs ci,

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -77,18 +77,42 @@ jobs:
       working-directory: Backend
       run: php artisan migrate:fresh --seed --env=testing --force
 
+
+    # -------------------------
+    #  Run backend tests
+    # -------------------------
+    - name: Run backend tests
+      working-directory: Backend
+      run: php artisan test --env=testing || echo "tests_failed=true" >> $GITHUB_OUTPUT
+
+    # -------------------------
+    #  Re-seed database for Playwright
+    # -------------------------
+    - name: Re-seed database for Playwright
+      working-directory: Backend
+      run: php artisan migrate:fresh --seed --env=testing --force
+
+    
+    # -------------------------
+    # 8. Setup Node.js 
+    # -------------------------
     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 20
         cache: npm
         cache-dependency-path: FrontEnd/package.json
-
+    
+    # -------------------------
+    #  Install backend dependencies securely
+    # -------------------------
     - name: Install frontend dependencies
       working-directory: FrontEnd
       run: npm ci
 
-    # --- CRITICAL: Environment MUST come BEFORE Build ---
+    # -------------------------
+    #  Create secure Laravel environment
+    # -------------------------
     - name: Prepare Frontend Environment
       working-directory: FrontEnd
       run: |
@@ -99,17 +123,20 @@ jobs:
         VITE_REVERB_PORT=8080
         VITE_REVERB_SCHEME=http
         EOF
-
+    
+    # -------------------------
+    # Build Vue frontend
+    # -------------------------
     - name: Build frontend
       working-directory: FrontEnd
       run: npm run build
-
+    
     - name: Install Playwright
       working-directory: FrontEnd
       run: npx playwright install --with-deps
 
     # -------------------------
-    # 12. Start Laravel and Vue servers
+    # . Start Laravel and Vue servers
     # -------------------------
     - name: Start Servers
       run: |
@@ -132,7 +159,7 @@ jobs:
     # 13. Run Playwright tests
     # -------------------------
     - name: Run Playwright tests
-      timeout-minutes: 8
+      timeout-minutes: 12
       working-directory:  FrontEnd/Playwright
       run: |
         npx playwright test
