change type

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,7 +101,8 @@ jobs:
     # -------------------------
     - name: Run backend tests
       working-directory: Backend
-      run: php artisan test --env=testing
+      run: php artisan test --env=testing || echo "tests_failed=true" >> $GITHUB_OUTPUT
+
 
     # -------------------------
     # 7. Re-seed database for Playwright
